import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import AppCard from "../components/AppCard";
import { RiSearchLine } from "react-icons/ri";
import { BsMicFill } from "react-icons/bs";
import { useSelector, useDispatch } from "react-redux";

const Home = (): any => {
  const { products } = useSelector((state: any): any => state.products);
  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="search mb-md d-block d-md-none">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <div className="header-search">
                <input
                  type="search"
                  placeholder="Search.."
                  className="form-control"
                />
                <div className="icon-left">
                  <RiSearchLine />
                </div>
                <div className="icon-right">
                  <BsMicFill />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="intro bg-secondary text-white">
        <div className="row align-items-center">
          <div className="col-lg-6 col-12">
            <div className="intro-text">
              <h2 className="fs-xxl text-white">Ecommerce Shop</h2>
              <p className="fs-xs">
                .It was popularised in the 1960s with the release of Letraset
                sheets containing Lorem
              </p>
              <Link href="#">
                <a className="btn btn-white">Shop Now</a>
              </Link>
            </div>
          </div>

          <div className="col-lg-6 col-12">
            <Image
              src="/images/headerBG.png"
              alt=""
              width="700"
              height="400"
              layout="responsive"
            />
          </div>
        </div>
      </section>

      <section className="categories mb-md">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-md-9 col-12">
              <div className="text-center pt-xl">
                <p className="fs-sm">
                  Ipsum passages, and more recently with desktop publishing
                  software like Aldus PageMaker including versions of Lorem
                  Ipsum
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="products pb-xl">
        <div className="container">
          <div className="title text-primary pb-md">
            <h3 className="fs-xl text-primary">Products :</h3>
          </div>
          <div className="row">
            {products.map((item: any, index: number): any => {
              return (
                <div className="col-lg-4 col-md-6 col-12 mb-md" key={item.id}>
                  <AppCard product={item} />
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
